In [1]:
#######################################################################
# Copyright (C)                                                       #
# 2016 Shangtong Zhang(zhangshangtong.cpp@gmail.com)                  #
# 2016 Kenta Shimada(hyperkentakun@gmail.com)                         #
# Permission given to modify the code as long as you keep this        #
# declaration at the top                                              #
#######################################################################

from __future__ import print_function
import numpy as np

WORLD_SIZE = 5
A_POS = [0, 1]
A_PRIME_POS = [4, 1]
B_POS = [0, 3]
B_PRIME_POS = [2, 3]
discount = 0.9

world = np.zeros((WORLD_SIZE, WORLD_SIZE))

# left, up, right, down
actions = ['L', 'U', 'R', 'D']

In [2]:
actionProb = []
for i in range(0, WORLD_SIZE):
    actionProb.append([])
    for j in range(0, WORLD_SIZE):
        actionProb[i].append(dict({'L':0.25, 'U':0.25, 'R':0.25, 'D':0.25}))

In [8]:
actionProb

[[{'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25}],
 [{'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25}],
 [{'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25}],
 [{'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25},
  {'D': 0.25, 'L': 0.25, 'R': 0.25, 'U': 0.25}],
 [{'D': 0.25, 'L': 0.25, 'R': 0.25, 

In [4]:
nextState = []
actionReward = []
for i in range(0, WORLD_SIZE):
    nextState.append([])
    actionReward.append([])
    for j in range(0, WORLD_SIZE):
        next = dict()
        reward = dict()
        if i == 0:
            next['U'] = [i, j]
            reward['U'] = -1.0
        else:
            next['U'] = [i - 1, j]
            reward['U'] = 0.0

        if i == WORLD_SIZE - 1:
            next['D'] = [i, j]
            reward['D'] = -1.0
        else:
            next['D'] = [i + 1, j]
            reward['D'] = 0.0

        if j == 0:
            next['L'] = [i, j]
            reward['L'] = -1.0
        else:
            next['L'] = [i, j - 1]
            reward['L'] = 0.0

        if j == WORLD_SIZE - 1:
            next['R'] = [i, j]
            reward['R'] = -1.0
        else:
            next['R'] = [i, j + 1]
            reward['R'] = 0.0

        if [i, j] == A_POS:
            next['L'] = next['R'] = next['D'] = next['U'] = A_PRIME_POS
            reward['L'] = reward['R'] = reward['D'] = reward['U'] = 10.0

        if [i, j] == B_POS:
            next['L'] = next['R'] = next['D'] = next['U'] = B_PRIME_POS
            reward['L'] = reward['R'] = reward['D'] = reward['U'] = 5.0

        nextState[i].append(next)
        actionReward[i].append(reward)

In [16]:
nextState

[[{'D': [1, 0], 'L': [0, 0], 'R': [0, 1], 'U': [0, 0]},
  {'D': [4, 1], 'L': [4, 1], 'R': [4, 1], 'U': [4, 1]},
  {'D': [1, 2], 'L': [0, 1], 'R': [0, 3], 'U': [0, 2]},
  {'D': [2, 3], 'L': [2, 3], 'R': [2, 3], 'U': [2, 3]},
  {'D': [1, 4], 'L': [0, 3], 'R': [0, 4], 'U': [0, 4]}],
 [{'D': [2, 0], 'L': [1, 0], 'R': [1, 1], 'U': [0, 0]},
  {'D': [2, 1], 'L': [1, 0], 'R': [1, 2], 'U': [0, 1]},
  {'D': [2, 2], 'L': [1, 1], 'R': [1, 3], 'U': [0, 2]},
  {'D': [2, 3], 'L': [1, 2], 'R': [1, 4], 'U': [0, 3]},
  {'D': [2, 4], 'L': [1, 3], 'R': [1, 4], 'U': [0, 4]}],
 [{'D': [3, 0], 'L': [2, 0], 'R': [2, 1], 'U': [1, 0]},
  {'D': [3, 1], 'L': [2, 0], 'R': [2, 2], 'U': [1, 1]},
  {'D': [3, 2], 'L': [2, 1], 'R': [2, 3], 'U': [1, 2]},
  {'D': [3, 3], 'L': [2, 2], 'R': [2, 4], 'U': [1, 3]},
  {'D': [3, 4], 'L': [2, 3], 'R': [2, 4], 'U': [1, 4]}],
 [{'D': [4, 0], 'L': [3, 0], 'R': [3, 1], 'U': [2, 0]},
  {'D': [4, 1], 'L': [3, 0], 'R': [3, 2], 'U': [2, 1]},
  {'D': [4, 2], 'L': [3, 1], 'R': [3, 3], 'U'

In [17]:
actionReward

[[{'D': 0.0, 'L': -1.0, 'R': 0.0, 'U': -1.0},
  {'D': 10.0, 'L': 10.0, 'R': 10.0, 'U': 10.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': -1.0},
  {'D': 5.0, 'L': 5.0, 'R': 5.0, 'U': 5.0},
  {'D': 0.0, 'L': 0.0, 'R': -1.0, 'U': -1.0}],
 [{'D': 0.0, 'L': -1.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': -1.0, 'U': 0.0}],
 [{'D': 0.0, 'L': -1.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': -1.0, 'U': 0.0}],
 [{'D': 0.0, 'L': -1.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': 0.0, 'L': 0.0, 'R': -1.0, 'U': 0.0}],
 [{'D': -1.0, 'L': -1.0, 'R': 0.0, 'U': 0.0},
  {'D': -1.0, 'L': 0.0, 'R': 0.0, 'U': 0.0},
  {'D': -1

In [7]:
world

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [23]:
while True:
    # keep iteration until convergence
    newWorld = np.zeros((WORLD_SIZE, WORLD_SIZE))
    for i in range(0, WORLD_SIZE):
        for j in range(0, WORLD_SIZE):
            for action in actions:
                newPosition = nextState[i][j][action]
                # bellman equation
                newWorld[i, j] += actionProb[i][j][action] * (actionReward[i][j][action] + discount * world[newPosition[0], newPosition[1]])
    if np.sum(np.abs(world - newWorld)) < 1e-4:
        print('Random Policy')
        print(newWorld)
        break
    world = newWorld

Random Policy
[[ 3.30899634  8.78929187  4.42761919  5.3223676   1.49217876]
 [ 1.52158807  2.99231786  2.25013995  1.90757171  0.54740271]
 [ 0.05082249  0.73817059  0.67311326  0.35818622 -0.40314114]
 [-0.9735923  -0.43549543 -0.35488226 -0.58560508 -1.18307508]
 [-1.85770055 -1.34523126 -1.22926726 -1.42291814 -1.97517904]]


In [32]:
world = np.zeros((WORLD_SIZE, WORLD_SIZE))
while True:
    # keep iteration until convergence
    newWorld = np.zeros((WORLD_SIZE, WORLD_SIZE))
    for i in range(0, WORLD_SIZE):
        for j in range(0, WORLD_SIZE):
            values = []
            for action in actions:
                newPosition = nextState[i][j][action]
                # value iteration
                values.append(actionReward[i][j][action] + discount * world[newPosition[0], newPosition[1]])
            newWorld[i][j] = np.max(values)
    if np.sum(np.abs(world - newWorld)) < 1e-4:
        print('Optimal Policy')
        print(newWorld)
        break
    world = newWorld

Optimal Policy
[[ 21.97744338  24.41938153  21.97744338  19.41938153  17.47744338]
 [ 19.77969904  21.97744338  19.77969904  17.80172914  16.02153504]
 [ 17.80172914  19.77969904  17.80172914  16.02153504  14.41938153]
 [ 16.02153504  17.80172914  16.02153504  14.41938153  12.97744338]
 [ 14.41938153  16.02153504  14.41938153  12.97744338  11.67969904]]
